---
title: 'Data Module'
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  word_document:
    reference_docx: ../Templates/template.docx
  html_document:
    df_print: paged
  pdf_document: default
bibliography: ../Bibliography/Climate-Change.bib
csl: ../Bibliography/chicago-fullnote-bibliography-with-ibid.csl
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      fig.height = 5, 
                      fig.pos = "H", 
                      out.extra = '',
                      tidy.opts=list(width.cutoff=50), 
                      tidy=TRUE)

```


# Abstract

Climate change data are vast and multi-faceted. This module uses greenhouse gas emissions data as a proxy to explore how various disaggregations of climate change data can paint different narratives in the global conversation on climate. In this module we will help students understand how emissions and their measured impacts in terms of climate-related disasters could impact the trajectory of international cooperation.

In the first part of the module students will learn how to access and retrieve raw data on emissions from two different datasets, and prepare it for analysis using data wrangling techniques and best practices. Through this specific process, students will learn about the timeliness and reliability of data by exploring missing data and how to report on it. 

The next section will ask to create several visualizations that look at how emissions can be aggregated differently and how these different aggregations can skew narratives of responsibility and mitigation efforts. They will explore the difference between reporting on CO~2~ exclusively versus complete GHG emissions inventories. They will also explore how international trade can change a country’s emissions narrative by changing the boundary condition to where emissions are allocated in order to exploit the net contributions to emissions at a global scale.


Finally, students may have the chance to explore the differential impacts of climate-related events by looking at disaster mortality data. They will first try to assess which climate hazards are the most deadly and which regions are affected the most. Students will also explore how the frequency of these events have changed over time, and which regions deserve the most urgent attention.

# Problem Set


You are a climate policy analyst working for a non-governmental organization participating in the next round of negotiations at the Conference of Parties. Your manager asks you to visualize the most recent data on GHG emissions to help defend your NGO's stance of __________(we could say something like defending “pick country of your choosing”) and to create a one-page memo that includes the following visualizations:

1. A map of only CO~2~ emissions by country.
2. A map of GHG emissions (minus CO~2~) by country.
3. A map of total GHG emissions by CO~2~ equivalent.
3. A map of net emissions by country.

The one-page memo should synthesize the data you've explored to answer some of the following analytical questions:

1. Which visualizations support your stance the best?
1. Who is the historically biggest emitter at this conference by each metric used above (CO~2~, GHG – CO~2~, GHG)?
2. What are some of the data deprivations that might affect your final analysis and assessment?


# Steps to complete the assignment



1. Clone the following repository into your local computer **[They will clone the raw data folder from our GitHub repository]**

2. Open the pre-formatted R markdown file to start your one-page memo.

3. Import your datasets (emissions data from UNFCCC[@Friedlingstein2020] and net contributions data from Global Carbon Project[@zotero-7988]) using `readxl` package

4. Clean your datasets

    1. Rename the column names in a consistent manner
    2. Recode the data types that's appropriate for analysis. Example, change year from charactor to factor, same with country names
    3. Convert data from wide to long to prepare for analysis
    4. Fill missing data with using simple data imputation methods to get a sense of how missing data is dealt with in the real world

5. Merge the two datasets based on country names and years using `tidyverse` package

6. Create maps using `ggplot2`





# References