---
title: 'Climate Change'
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  word_document:
    reference_docx: ../Templates/template.docx
  html_document:
    df_print: paged
  pdf_document: default
bibliography: ../Bibliography/Climate-Change.bib
suppress-bibliography: true
csl: ../Bibliography/chicago-fullnote-bibliography-with-ibid.csl
---


```{r setup-00, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      fig.height = 5, 
                      fig.pos = "H", 
                      out.extra = '',
                      tidy.opts=list(width.cutoff=50), 
                      tidy=TRUE)

```

```{r child = '01-Introduction.Rmd'}
```

```{r child = '02-History.Rmd'}
```

```{r child = '03-Data-Landscape-Emissions.Rmd'}
```

```{r child = '03-Data-Landscape-Finance.Rmd'}
```

```{r child = '03-Data-Landscape-Vulnerability.Rmd'}
```

```{r child = '04-Data-Politics-Emissions.Rmd'}
```

```{r child = '04-Data-Politics-Finance.Rmd'}
```

```{r child = '04-Data-Politics-Vulnerability.Rmd'}
```

```{r child = '05-Conclusion.Rmd'}
```