---
bibliography: ../Bibliography/Climate-Change.bib
csl: ../Bibliography/chicago-fullnote-bibliography-with-ibid.csl
---

## Climate Finance

Understanding the landscape of a few different data/indicators helps us to understand the current state of adaptation and mitigation, how do we track action, accountability, and political will to change the outcomes related to those data? In other words, how do we know that initiatives to adapt to climate change or to mitigate emissions are being supported and whether or not developed countries are upholding their commitments to developing countries? One possible pathway to do so is through looking at climate change finance. 

In the SDG 13, we can look directly at Indicator 13.a.1 which states its target to "Implement the commitment undertaken by developed-country parties to the United Nations Framework Convention on Climate Change to a goal of mobilizing jointly $100 billion annually by 2020 from all sources to address the needs of developing countries in the context of meaningful mitigation actions and transparency on implementation and fully operationalize the Green Climate Fund through its capitalization as soon as possible"

Looking at the metadata for this specific indicator, you will quickly learn that "there are no agreed upon indicators to track progress on the joint goal of mobilizing scaled up climate finance in the context of USD 100 billion goal by 2020 and through to 2025."[@UNFCCC] Given this clear data deprivation, what can we measure to figure out what action is being taken toward this Goal 13 target? And further down the line, how might this deprivation drive the political conversation on finance or how might this data deprivation be driven by politics?

- Visual: table of ten biggest/most prominent Climate Funds and descriptions of their purpose, data, types of finance(ODA), adaptation/mitigation, who tracks data, how often collected

As you can see in Table 13.X, each climate-related fund has their own method for collecting data and each has their own specific entity for tracking pledges and contributions. Most of the funds are linked to a Multilateral Development Bank (MDB) and count on the banks, or entities like the OECD or the UNFCCC to build the process for data collection and criteria for each funds' disbursements. Further complicating these dynamics, there is no one definition of what qualifies as climate finance, either. In an attempt to do just that, the OECD Development Assistance Committee (DAC) Rio Makers for climate adaptation and mitigation (Table 13.xx) established criteria for finance eligibility in 2010 and is one of the most referenced frameworks for determining whether or not projects are adequately linked to climate change.[@OECD2016a] These marker's validity, however, are recently being critiqued as an inadequate litmus test, especially for adaptation related finance projects. Despite these questions, the Rio Markers remain one of the more reliable measures for verifying the climate nature of development and purported climate projects' validity.[@Weikmans2017a]

- Visual: Table with Rio+ Markers for Adaptation and Mitigation

Whether or not loans count as climate finance as opposed to grants, or if any development aid that might meet a Rio Marker qualifies as climate finance, or even to what extent a project needs to focus on climate change are all debates that countries have yet to resolve. What we do know for certain is that the most commonly available data for us to identify are country pledges to climate finance particularly through the UNFCCC processes- but this does not tell us the whole story. For example, take the Green Climate Fund (refer to Text Box 13xx, pg. xx), whose governance is perhaps more straightforward than many funding mechanisms above: by looking exclusively at pledges, we are unable to see whether or not money has actually been contributed to the fund and even more than that- whether or not that money has a purpose and has been disbursed, or used. Given the complexity of climate finance data, we'll do most of our exploration of the deprivations, availability of information, and manipulations of information in the next section on the Politics of Data.  

