---
bibliography: ../Bibliography/Climate-Change.bib
csl: ../Bibliography/chicago-fullnote-bibliography-with-ibid.csl
---

## Climate Finance

*[Opening Textbox will include a few different quotes showing the varying predictions of finance needed to address climate change. These are two examples of what that will look like, but with a little less detail and more numbers:*

*"Meanwhile the GHF, a think-tank commissioned by Kofi Annan, estimated that economic losses globally attributed to climate change amount to more than US\$125 billion a year, and are estimated to rise to US \$600 billion by 2030 (GHF 2009:1). Given this context, what can be expected from current efforts to curb global emissions and achieve climate justice?"(Bracking 2015, 281)*

*"The UN's Intergovernmental Panel on Climate Change (IPCC) says that an annual investment of \$2.4 trillion is needed in the energy system alone until 2035 to limit temperature rise to below 1.5*$^\circ$C from pre-industrial levels. (That is around 2.5% of the world's economy.)"(Yeo 2019)]

<https://www.flickr.com/photos/wedoworldwide/23565325642/>

By now you're familiar with the data and political landscapes of both mitigation and adaptation- do you agree with the assessment that this project, highlighted in Oxfam's 2020 Climate Finance Shadow Report, is not an appropriate climate-related project?

> In 2017--18, Japan reported over \$700m in climate finance towards its 'Matarbari Ultra Super Critical Coal-Fired Power Project' in Bangladesh.^14^ Japan defends the loan as climate finance because the plant produces less greenhouse gas emissions than a similarly sized plant using subcritical technology.^15^ But as fossil fuels contribute to climate change, the loans should not be counted as climate finance. Lack of transparency makes it hard to assess whether other countries have also reported coal projects to the UNFCCC in 2017--18. The Japanese Environment Minister recently signalled that Japan would phase out such financing, though the move has drawn criticism for being too equivocal."[@Carty2018]

One of the few positive outcomes of COP14 in Copenhagen in 2009 was the plan for developed countries to contribute \$100 billion annually to developing countries by 2020, specifically "new and additional resources."[@UNFCCC2010] Given the increasingly urgent need for adaptation and mitigation efforts as the impacts of climate change intensified around the world at this time, this proposal was well received. But the actual implementation of this finance stream, as you have noted from the metadata for Goal 13, has not been realized more than a decade later. Questions of who is accountable to track this finance, where will it be housed, what projects will be eligible, and especially which financial contributions by developed countries count toward this specific goal are a part of all climate finance related conversations. These disagreements, particularly between developed and developing countries, have stalled climate financing and reaching the goal of mobilizing \$100 billion USD annually by 2020.[@Weikmans2017a]

As we discussed in the overview of our data in the last section, there are many funds that are related to climate change or have climate change mitigation or adaptation as their mandate. But what happens when projects that aren't related to climate change need funding? Isn't everything related to climate? So what criteria are determining what is or isn't a climate-related project? What we see in the political landscape is a seemingly purposeful watering down of what counts as climate-related or loose mentions of climate change within development projects in order to access this growing funding stream.[@Michaelowa2011] This can be defined as "***Greenwashing***," in other words, making something appear to benefit the environment or contributing to climate solutions when they do not substantially do so.[@Delmas2011a] According to a 2011 review of 10,414 projects coded as climate-related by contributors, less than half of these projects had clear contributions to adaptation or mitigation and a further third of the projects were inappropriately coded as climate change when it was clear they were not.[@Delmas2011a]

This dilemma has continued into the present day as detailed by a 2020 report by Oxfam which further this argument and poses the growing concern that climate finance is being over-reported. According to the report, not only do they estimate that the climate-relevance of reported projects may be a third less than report, the amount of total climate finance reported by the UNFCCC and OECD, totals of \$59.5 billion between 2017-2018, are likely to be significantly over the actual climate-specific finance adjusted based on grant equivalence, which they estimate to be closer to somewhere between \$19-22.5 billion, with only \$6-7 billion of those funds going to adaptation-specific projects.[@Carty2018] Beyond questions about classification are matters of over-reporting in climate finance metrics and possible co-benefits, such as predicted prevented emissions (See GCF Text Box 13.xx). What's a reason that western/developed countries might be over-estimating the amount of climate finance mobilized?

Having clear and transparent data is a matter of political importance for achieving SDG Traget 13.a.1, but also for actually addressing the most vulnerable communities needs for mitigation, and more importantly, adaptation efforts. In a report by IIED, researchers found that less than 10% of climate finance from international climate funds reaches local communities through community-level projects and activists by 2016. The report also estimated that "out of the US\$17.4 billion total, less than 10% (\$1.5 billion) was approved for locally focused climate change projects between 2003 and 2016."[@2019n]

To improve these disparities and to increase the success of funding initiatives, climate justice advocates and activists have pointed to the need to change the design of climate financing which was founded on Western ideals and wants.[@Abimbola2021] What's further, there are accounts of the exclusive nature of finance processes that prevent the participation of most-impacted communities in design, metrics, and implementation. According to a report on racial injustices in climate proceedings, "Indigenous Peoples and other marginalized groups are ignored at all levels of decision making. The lack of engagement with unequal power relationships in both adaptation research and practice can lead to adaptation interventions that do not benefit the poorest and most marginalized. In some cases, local communities even resort to blocking the implementation of adaptation measures, as one of the very few tools available to those whose voices are not heard in the design of policies and interventions that intimately affect their lives."[@Abimbola2021]

A big part of this resistance is to the growing amount of loans used in place of grants, or as ___Official Development Assistance___ (ODA) classifies differences between concessional(ex: grants) and non-concessional(ex: loans) funds.[@OECD2021] (see chapter xx, page xx) [More will be added to this point later, linking to need for more adaptation funding]

If you decide that you want to look further into climate finance, something you will notice is the propensity to cite the pledges that countries have made. Take note: do these sources also talk about whether or not the money has actually been contributed to the fund they've pledged to? Has the contribution been mobilized into an actual project? What kind of finance is it? Is it a loan that countries will need to pay back or is it a grant? 

___[GCF Text Box 13.xx]___

The Green Climate Fund (GCF) was established in the same section of the Copenhagen Accord at COP15 as the \$100 Billion finance commitment.[@UNFCCC2010] While there has long been speculation that the GCF would hold most of the "new and additional resources," experts continue to debate whether that is the actual purpose of this newer climate fund.[@Mathy2016] [@Soanes2017] [@Seo2019] "The core of the Green Climate Fund's (GCF) mandate comes from Article 2(c) of the Paris Agreement, which "aims to strengthen the global response to the threat of climate change ... by making finance flows consistent with a pathway towards low greenhouse gas emissions and climate-resilient development."[@GreenClimateFund2019] Unlike many other funds, the GCF is supposed to fund a 50:50 split between adaptation and mitigation projects. As of 2021, more than 60% of the approved projects were mitigation-based with a clear lag in adaptation projects being approved.[@GreenClimateFund2021]

The GCF is an interesting fund for us to explore together, because it has many of the symptoms of the data deprivations, over-reporting, and deviations from ODA that epitomize the distrust between developed and developing countries. 

- __Selection Criteria__: Not based on Rio Markers; are prioritized by potential emissions reductions, favoring mitigation over adaptation projects; 

- __Over-Reporting__: there is little accountability as to the progress of approved projects or the validity of the measurements- these are all country-reported; there are a lack of incentives for countries to report accurately; in 2021 the GCF found that there has been an average of 

- __Lack of Contribution Transparency__: The data we'll be exploring in our module are ___Climate Finance Pledges___ made to the GCF.[@GreenClimateFund2021] Not only are the pledges not measured in grant-equivalency (so when countries pledge money to the fund, they can actually be over-representing how much they will actually contribute), but they do not reflect whether or not that finance will end up in the Bank or dispersed to projects.[@OECD2016]

## Conclusions from Finance Section

Moving forward, to meet the \$100 billion climate finance commitment countries will need to decide what is and what is not climate finance, who should monitor and collect the data related to these projects, and make clear the role of most-impacted countries and communities, especially indigenous peoples' ability to engage directly in the formation of these standards.
