--- 
title: "Climate Change"
date: "`r format(Sys.time(), '%d %B, %Y')`"
site: bookdown::bookdown_site
documentclass: book
bibliography: ../Bibliography/Climate-Change.bib
#suppress-bibliography: true
csl: ../Bibliography/chicago-fullnote-bibliography-with-ibid.csl
---

```{r include=FALSE}
library(knitr)
library(officedown)
library(officer)
library(magrittr)
library(ggplot2)
opts_chunk$set(echo = TRUE, warning = FALSE,
                      fig.cap.style = "Image Caption",
                      fig.cap.pre = "Figure 13.",
                      fig.cap.sep = ": ",
                      out.extra = '',
                      tidy.opts=list(width.cutoff=50), 
                      tidy=TRUE)
```


```{r child = "01-Introduction.Rmd"}
```

```{r child = "02-History.Rmd"}
```

```{r child = "03-Data-Landscape-Emissions.Rmd"}
```

```{r child = "03-Data-Landscape-Finance.Rmd"}
```

```{r child = "03-Data-Landscape-Vulnerability.Rmd"}
```

```{r child = "04-Data-Politics-Emissions.Rmd"}
```

```{r child = "04-Data-Politics-Finance.Rmd"}
```

```{r child = "04-Data-Politics-Vulnerability.Rmd"}
```

```{r child = "05-Conclusion.Rmd"}
```


# Endnotes

# Bibliography


<!--chapter:end:index.Rmd-->

